CREATE TABLE IF NOT EXISTS User (
  UserId INT PRIMARY KEY,
  Username VARCHAR(255) NOT NULL,
  Password VARCHAR(255) NOT NULL,
  Salt VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Probe (
  ProbeId INT PRIMARY KEY,
  Name VARCHAR(255) NOT NULL,
  UserId INT NOT NULL,
  Password VARCHAR(255) NOT NULL,
  Salt VARCHAR(255) NOT NULL,
  FOREIGN KEY (UserId) REFERENCES User(UserId)
);

CREATE TABLE IF NOT EXISTS Monitoring (
  MonitorId INT PRIMARY KEY,
  StartDate DATETIME NOT NULL,
  EndDate DATETIME,
  ProbeId INT NOT NULL,
  FOREIGN KEY (ProbeId) REFERENCES Probe(ProbeId)
);

CREATE TABLE IF NOT EXISTS Data (
  DataId INT PRIMARY KEY,
  Value FLOAT NOT NULL,
  Timestamp DATETIME NOT NULL,
  MonitorId INT NOT NULL,
  FOREIGN KEY (MonitorId) REFERENCES Monitoring(MonitorId)
);

CREATE TABLE IF NOT EXISTS Session (
  SessionId INT PRIMARY KEY,
  UserId INT NOT NULL,
  Expiration DATETIME NOT NULL,
  FOREIGN KEY (UserId) REFERENCES User(UserId)
);
