CREATE TABLE IF NOT EXISTS User (
  UserId INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(255) NOT NULL,
  Firstname VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  Password VARCHAR(255) NULL
);

CREATE TABLE IF NOT EXISTS Probe (
  ProbeId INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(255) NOT NULL,
  UserId INT NOT NULL,
  Password VARCHAR(255) NULL,
  FOREIGN KEY (UserId) REFERENCES User(UserId)
);

CREATE TABLE IF NOT EXISTS Monitoring (
  MonitorId INT AUTO_INCREMENT PRIMARY KEY,
  StartDate DATETIME NOT NULL,
  EndDate DATETIME,
  ProbeId INT NOT NULL,
  FOREIGN KEY (ProbeId) REFERENCES Probe(ProbeId)
);

CREATE TABLE IF NOT EXISTS Data (
  DataId INT AUTO_INCREMENT PRIMARY KEY,
  TempValue FLOAT NOT NULL,
  FloatDensityValue FLOAT NOT NULL,
  RefractDensityValue FLOAT NOT NULL,
  Timestamp DATETIME NOT NULL,
  MonitorId INT NOT NULL,
  FOREIGN KEY (MonitorId) REFERENCES Monitoring(MonitorId)
);

CREATE TABLE IF NOT EXISTS Session (
  SessionId INT AUTO_INCREMENT PRIMARY KEY,
  UserId INT NOT NULL,
  Expiration DATETIME NULL,
  FOREIGN KEY (UserId) REFERENCES User(UserId)
);
