version: '3.8'

services:
  mariadb: 
    image: mariadb:latest
    container_name: mariadb
    restart: always
    env_file: 
      - ./.env
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_USER: $MARIADB_USER
      MARIADB_PASSWORD: $MARIADB_PASSWORD
      MARIADB_DATABASE: $MARIADB_DATABASE
    volumes:
      - ./db/dbData:/var/lib/mariadb
      - ./db/dbScripts:/docker-entrypoint-initdb.d
    ports:
      #- "5000:3306"
      - "3306:3306"
    networks:
      - api-db

  api:
    build: ./api
    container_name: api
    restart: always
    volumes:
      - ./api:/api
    ports:
      - "3001:3001" # to allow testing from postman
    depends_on:
      - mariadb
    command: "npm start"
    networks:
      - api-db
      - front-api

  frontend:
    build : ./client
    container_name: frontend
    restart: always
    volumes : 
      - ./client:/client
    ports:
      - "3000:3000"
    depends_on:
      - mariadb 
      - api
    #command: "npm start"
    networks:
      - front-api
    #network_mode: "host" # for dev purposes, so -> NO # check

networks:
    api-db:
      driver: bridge
    front-api:
      driver: bridge
    