version: '3.8'

services:
  mariadb: 
    image: mariadb:latest
    container_name: mariadb
    restart: always
    env_file: 
      - ./.env
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_USER: $MARIADB_USER
      MARIADB_PASSWORD: $MARIADB_PASSWORD
      MARIADB_DATABASE: $MARIADB_DATABASE
    volumes:
      - ./db/dbData:/var/lib/mariadb
      - ./db/dbScripts:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - api-db
    
    

  api:
    build: ./api
    container_name: api
    restart: always
    volumes:
      - ./api:/api
      - /etc/letsencrypt/archive/www.alexandre.doneux.eu:/etc/letsencrypt/archive/www.alexandre.doneux.eu
      - /api/node_modules/
    ports:
      #- "3001:3001" # to allow testing from postman
      - "8443:443" #HTTPS
    depends_on:
      - mariadb
    command: "npm start"
    networks:
      - api-db
      - front-api


  frontend:
    build : ./client
    container_name: frontend
    restart: always
    #env_file: 
    #  - ./.env
    #environment:
      #CERT_PATH: $CERT_PATH
      #KEY_PATH: $KEY_PATH
    volumes : 
      - ./client:/client
      - ./client/sites-enabled:/etc/nginx/sites-enabled/
      - ./client/.nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/    
      - /client/WAF.sh:/client/WAF.sh
      - /client/node_modules/
    ports:
      - "80:80" #port 80 redirect to https
      - "443:443"
    depends_on:
      - mariadb 
      - api
    #command: "npm start"
    networks:
      - front-api
    #network_mode: "host" # for dev purposes, so -> NO # check


networks:
    api-db:
      driver: bridge
    front-api:
      driver: bridge
    
