version: '3.8'

services:
  mariadb: 
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    env_file: ./.env
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_USER: $MARIADB_USER
      MARIADB_PASSWORD: $MARIADB_PASSWORD
      MARIADB_DATABASE: $MARIADB_DATABASE
    volumes:
      - ./db:/var/lib/mariadb
    ports:
      #- "5000:3306"
      - "3306:3306"

  api:
    build: ./api
    container_name: api
    restart: unless-stopped
    volumes:
      - ./api:/api
    ports:
      - "3001:3001"
    depends_on:
      - mariadb
    command: "npm start"
